apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bs9jsz45w-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bs9jsz45w-nodejs 
  name: bs9jsz45w-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bs9jsz45w-nodejs 
